apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
spec:
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
  containers:
  # ここの名前はなんでも良い
  - name: gop
    image: kodekloud/fileserver
    volumeMounts:
    - name: data-store
      mountPath: /web